### ISSUE TITLE
Discord server link does not work

### ISSUE THREAD

**Issue by dko1905** [croxywastaken/croxydb#3]
The discord [server link](https://discord.gg/mswG4px), in the README, does not work.

**Comment by croxydev** [comment]
Discord server is closed. You can contact me from this tag: croxy#1891

**Comment by dko1905** [comment]
@croxywastaken You are not accepting friend requests on Discord.
![image](https://user-images.githubusercontent.com/44919636/107652388-cfa14b00-6c80-11eb-8353-165a62f50e4f.png)
